AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable

require: rubocop-rspec

inherit_from: .rubocop_todo.yml

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Max: 100
  Exclude:
    - spec/**/*

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
